WIP: blog: config.yml: add workaround
Logs:

λ ./scripts/local-preview.sh
Start building sites …
hugo v0.92.1-85E2E862 linux/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
ERROR 2025/04/14 12:02:15 instagram shortcode: Missing config value for services.instagram.accessToken. This can be set in config.toml, but it is recommended to configure this via the HUGO_SERVICES_INSTAGRAM_ACCESSTOKEN OS environment variable. If you are using a Client Access Token, remember that you must combine it with your App ID using a pipe symbol (<APPID>|<CLIENTTOKEN>) otherwise the request will fail.
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-missing-instagram-accesstoken"]
Error: Error building site: logged 1 error(s)
Built in 4059 ms

Signed-off-by: Daniil Klimuk <daniil.klimuk@3mdeb.com>